export const services = {
  features: [
    'Price',
    'Counter',
    'Devices',
    'Free Trail',
    'Cancel Anytime',
    'HDR',
    'Dolby Atmos',
    'Ad - Free',
    'Offline Viewing',
    'Family Sharing',
  ],
  basic: [
    '$9.99/Month',
    'Access to a wide selection of movies and shows, including some new releases.',
    'Watch on one device simultaneously',
    '7 Days',
    'Yes',
    'No',
    'No',
    'No',
    'No',
    'No',
  ],
  standard: [
    '$12.99/Month',
    'Access to a wider selection of movies and shows, including most new releases and exclusive content',
    'Watch on one device simultaneously',
    '7 Days',
    'Yes',
    'Yes',
    'No',
    'No',
    'Yes, for select titles.',
    'Yes, up to 5 family members.',
  ],
  premium: [
    '$14.99/Month',
    'Access to a widest selection of movies and shows, including all new releases and Offline Viewing',
    'Watch on one device simultaneously',
    '7 Days',
    'Yes',
    'Yes',
    'Yes',
    'Yes',
    'Yes, for all titles.',
    'Yes, up to 6 family members.',
  ],
}
